version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  redpanda:
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    # NOTE: Please use the latest version here!
    image: docker.vectorized.io/vectorized/redpanda:v21.7.6
    container_name: redpanda-1
    ports:
    - 9092:9092
    - 29092:29092
  # api:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - redpanda
  #     - redis
  # worker:
  #   build: .worker
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - redpanda
  #     - redis
