// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	entities "github.com/sdil/jkjav-server/pkg/entities"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateStation provides a mock function with given fields: _a0
func (_m *Repository) CreateStation(_a0 *entities.Station) (*entities.Station, error) {
	ret := _m.Called(_a0)

	var r0 *entities.Station
	if rf, ok := ret.Get(0).(func(*entities.Station) *entities.Station); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Station)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*entities.Station) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadStation provides a mock function with given fields: location, date
func (_m *Repository) ReadStation(location string, date string) (*entities.Station, error) {
	ret := _m.Called(location, date)

	var r0 *entities.Station
	if rf, ok := ret.Get(0).(func(string, string) *entities.Station); ok {
		r0 = rf(location, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Station)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(location, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
