basePath: /
definitions:
  main.PPV:
    properties:
      availability:
        example: 10
        type: integer
      date:
        example: "20210516"
        type: string
      location:
        example: PWTC
        type: string
    type: object
  main.User:
    properties:
      address:
        example: Kuala Lumpur
        type: string
      date:
        example: "20210516"
        type: string
      firstName:
        example: Fadhil
        type: string
      lastName:
        example: Yaacob
        type: string
      location:
        example: PWTC
        type: string
      mysejahteraId:
        example: "900127015527"
        type: string
      phoneNumber:
        example: "0123456789"
        type: string
    type: object
info:
  contact: {}
  description: High performant JKJAV API Server
  title: JKJAV API Server
  version: "1.0"
paths:
  /list-ppv:
    get:
      consumes:
      - application/json
      description: Get PPV slots by state
      parameters:
      - description: list PPV by state. The only available option is PWTC
        in: query
        name: state
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.PPV'
            type: array
      summary: List PPV
  /submit:
    post:
      consumes:
      - application/json
      description: Submit vaccine booking slot
      parameters:
      - description: User info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.User'
      summary: Submit
swagger: "2.0"
