basePath: /
definitions:
  entities.Station:
    properties:
      availability:
        example: 10
        type: integer
      date:
        example: "20210516"
        type: string
      location:
        example: PWTC
        type: string
    type: object
info:
  contact: {}
  description: High performant JKJAV API Server
  title: JKJAV API Server
  version: "1.0"
paths:
  /stations/{name}:
    get:
      consumes:
      - application/json
      description: Get station slots by location
      parameters:
      - description: select the location. The only available option is PWTC
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Station'
            type: array
      summary: List Station
swagger: "2.0"
